const mongoose=require('mongoose')

const orderSchema=mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            require:true
        },
        country:{
            type:String,
            require:true
        },
        state:{
            type:String,
            require:true
        },
        city:{
            type:String,
            require:true
        },
        phoneNo:{
            type:String,
            require:true
        },
        postalCode:{
            type:String,
            require:true
        }
    },
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user',
        required:true
    },
    orderItems:[{
        name:{
            type:String,
            require:true
        },
        quantity:{
            type:Number,
            require:true
        },
        image:{
            type:String,
            require:true
        },
        price:{
            type:Number,
            require:true
        },
        product:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Product',
            require:true
        },
    }],
    totalPrice:{
        type:Number,
        require:true
    },
    shippingPrice:{
        type:Number,
        require:true
    },
    taxPrice:{
        type:Number,
        require:true
    },
    paymentInfo:{
        id:{
            type:String
        },
        status:{
            type:String
        }
    },
    orderStatus:{
        type:String,
        default:"pending",
        require:true
        
    },
    paidAt:{
        type:Date,
        default:Date.now
    },
    shippingAt:{
        type:Date,
        default:Date.now
    },
    createdAt:{
        type:Date,
        default:Date.now
    }
})

let orderModel=mongoose.model('order',orderSchema)

module.exports=orderModel